stages:
  - build
  - test
  - quality
  - deploy

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/
  policy: pull-push
  unprotect: false
  untracked: false
  when: on_success

image: node:18.11.0



build:
  stage: build
  before_script:
  - npm install
  script:
    - npm run build

test:
  stage: test
  before_script:
  - npm install
  allow_failure: true
  script:
    - npm run test
  dependencies:
    - build

quality:
  stage: quality
  before_script:
  - npm install
  script: npm run lint > quality_nest.json
  artifacts:
    when: always
    reports:
        codequality:
            - quality_nest.json
  dependencies:
    - build
    - test

deploy:
  stage: deploy
  image: docker:20.10.23
  services:
    - docker:dind
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production 
  script:
    - docker login -u 'mahatokyh' -p '#lsatvph25.' docker.io
    - docker build -t mahatokyh/musica_nest:master .
    - docker push mahatokyh/musica_nest:master
  dependencies:
      - build
      - test
  
  