apiVersion: v1
kind: Service
metadata:
  name: musica-nest-service
  namespace: developpement
spec:
  type: ClusterIP
  ports:
    - targetPort: 3000
      port: 3000
  selector:
    app: musica-nest-label